Refactored preprocessing
as-ideas/ForwardTacotron pull request #103
Opened 2023-07-29 15:05 UTC by alexteua

Using torchaudio and batched processing where possible
General cleanup

2023-08-14 10:17 UTC, cschaefer26 requested changes
- torchaudio missing in requirements.txt
- tests not passing
- could be useful to add a test for some of the changed audio processing, e.g testing if the batched processing yields the exact same results as non-batched
- bug in preprocessing (voice_encoder running on wrong input)

2023-08-14 10:17 UTC, cschaefer26 commented on utils/dsp.py
>      def griffinlim(self, mel: np.array, n_iter=32) -> np.array:
I would suggest to use the same type (torch.Tensor) for all functions to be consistent (now some run on np.arrays and some on tensors)

2023-08-15 06:46 UTC, alexteua commented on configs/multispeaker.yaml
> +  target_dBFS: -30                      # Target loudness in decibels, used for normalization
@cschaefer26 it's for the reference wav processing, and yes it's always applied, the same as it was in the old preprocessing

2023-08-22 14:44 UTC, cschaefer26 approved these changes

2023-08-22 15:35 UTC, alexteua commented on preprocess.py
> +    dataloader = DataLoader(tts_dataset,
They are sorted by length in the TTSDataset, and then shuffle is set to False for the Dataloader, so the batches are created on a sorted data.

2023-08-22 15:36 UTC, merged